services:
  server:
    build: streamer
    ports: 
      - 8000:8080
    depends_on:
      - minio 
      - db
      - redis

  crud:
    build: crud_platform
    ports: 
      - 8001:8080
    depends_on:
      - minio 
      - db
      - redis
      


  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "exam_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "change_me"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: change_me
    command: server --console-address ":9001" /data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /d–∞ta:/root/redis
    environment:
      - REDIS_PASSWORD=change_me
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  minio_storage: {}

