services:
  server:
    build: server/
    ports: 
      - 8000:8080

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "exam_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "change_me"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

